service: aws-java-simple-http-endpoint

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: eu-west-1

package:
  artifact: target/naitiveClient-1.0-SNAPSHOT-shaded.jar

functions:
  block:
    handler: naitiveClient.naitiveClientAPI.LambdaNaitiveClientBlocksHandler
    events:
      - http:
          path: ping
          method: get
